#!/bin/bash



#-------------------- Basic Setup --------------------#

# Initialize Keybinds
sxhkd &

# Initialize Background
nitrogen --restore &

# Initialize Compositor
compton &


#-------------------- Basic Appearance --------------------#

bspc config border_width	0
bspc config window_gap		20
bspc config split_ratio		0.5
bspc config automatic_scheme	split


#-------------------- Mouse Setup --------------------#

# Set mouse cursor to look normal
xsetroot -cursor_name left_ptr

# Anything mouse hovers over goes into focus
bspc config focus_follows_pointer	true



#--------------------Set Up Workspaces--------------------#
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
